create table carros(
  modelo varchar(50),
  marca varchar(50),
  tipoVeiculo varchar(50),
  ano integer,
  quilometragem integer,
  potenciaMotor decimal,
  combustivel varchar(50),
  cambio varchar(50),
  direcao varchar(50),
  cor varchar(50),
  portas integer,
  finalPlaca integer,
  vidroEletrico integer,
  travaEletrica integer,
  arCondicionado integer,
  direcaogidraulica integer,
  som integer,
  airBag integer,
  alarme integer,
  sensorRe integer,
  cameraRe integer,
  blindado integer,
  valor decimal
)